Repository Nelwell/Awesomest-Project-Everest, pull requests merged in 2021-03, with the labels that each got.

#21 Added password validator 8 characters, 1 Uppercase, 1 Lowercase, 1 Number. Special Chars optional
  tests/test_validation.py
  validation/validate.py
Labels: UserInteraction, enhancement

#19 add ability to take in a US address through the use of a Location obj…
  api/location.py
  requirements.txt
  tests/test_location.py
Labels: Navigation

#29 Bing api trip
  .gitignore
  __init__.py
  api/bus.py
  api/validate.py
  tests/test.json
  tests/test_apis.py
  tests/test_validation.py
  validate.py
Labels: API Package, Navigation, help wanted
